name = "FisCom"
uuid = "38ca13f3-8ecc-4ee2-b3e1-b19c850c9bdd"
authors = ["ModifiedBear <albertorbiestro@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
